### ISSUE TITLE
Create mechanism for controlling page transitions

### ISSUE THREAD

**Issue by grassdog** [BeaverLodge/angular-cordova-mobile-prefab#2]
Rather than a global transition style by platform. It would be nice to control transitions per page.

**Comment by thenathanjones** [comment]
Referenced pull request addresses this issue by creating a directive for pages. The default transition will be a fade in/out but the transitions can be controlled by enter-transition and exit-transition attributes on the page directive.

**Comment by thenathanjones** [comment]
Superceded by #14
